# -*- coding: utf-8 -*-
"""1-) Exercicios_de_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qEORzAY1z2sUSPWqzN7KaqaoKkOqv6y5

Atividade 1: Imprimindo Mensagens
"""

print("Olá, mundo!")

"""Atividade 2: Variáveis e Entrada de Usuários"""

nome=input("Qual é o seu nome?")
idade=input("Qual é a sua idade?")
print("Olá," +nome+ "! Você " +idade+"anos.")

nome=input("Qual é o seu filme prefirido?")
ano=input("Qual foi o ano do seu lançamento?")
print("Seu filme prefirido é: " +nome+ "! Ele foi lançado no ano de  " +ano+".")

"""Atividade 3: Realizando operações matemáticas básicas"""

a = 5
b = 3
soma = a+b
produto = a*b
print ("Soma:",soma)
print ("produto:", produto)

a = 2
b = 3
soma = a+b
subtracao = a-b
produto = a*b
print ("Soma:",soma)
print ("Subtração:", subtracao)
print ("Soma:",soma)
print ("produto:", produto)

"""Atividade 4: Estrutura Condicionais"""

idade = int(input("Qual é a sua idade?"))
if idade >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")

temperatura = int(input("Qual é a temperatura atual?"))
if temperatura >= 30:
    print("Está quente")
else:
    print("Está frio")

"""Atividade 5: Laços de Repetição"""

for i in range(5):
    print("Está é a repetição número", i+1)

for i in range(10):
    print("Está é a repetição número", i+1)

"""Atividade 6: Somatório com While"""

soma = 0
contador = 1
while contador <= 5:
    soma += contador
    contador += 1
    print("A soma dos números de 1 a 5 é:", soma)

soma = int(input("Digite um número:"))
contador = 1
while contador <= 5:
    soma += contador
    contador += 1
    print("A soma dos números é:", soma)

"""Atividade 7: Trabalhando com Listas"""

frutas = ["maçã", "banana", "laranja"]
frutas.append("uva")
for item in frutas:
    print("item:", item)

Lista_de_compras = ["maça", "banana", "morango"]
Lista_de_compras.append("caja")

# Pergunta ao usuário qual fruta adicionar
fruta = input("Digite o nome da fruta que deseja adicionar: ")
Lista_de_compras.append(fruta)

# Exibe a lista de compras
for item in Lista_de_compras:
    print("compras:", item)

"""Ativadade 8: Criando Funções"""

def saudacao(nome):
    print("Olá,", nome + "!")

saudacao("Maria")  # Chama a função com "Maria" como argumento

def par_ou_impar(numero):
    if numero % 2 == 0:
        return "par"
    else:
        return "ímpar"

# Exemplo de uso
numero = int(input("Digite um número: "))
resultado = par_ou_impar(numero)
print(f"O número {numero} é {resultado}.")

"""Ativade 9: Manipulação de Strings"""

texto = "Python é incrível!"
print(texto.upper()) # Converte para maiúsculas
print(texto.replace("incrível", "poderoso")) # Substitui uma palavra

# Função para contar a ocorrência de uma letra na frase
def contar_letra(frase, letra):
    return frase.count(letra)

# Pede ao usuário uma frase
frase = input("Digite uma frase: ")

# Pede ao usuário a letra que deseja contar
letra = input("Digite a letra que deseja contar: ")

# Conta e exibe a quantidade de vezes que a letra aparece
quantidade = contar_letra(frase, letra)
print(f"A letra '{letra}' aparece {quantidade} vez(es) na frase.")

"""Atividade 10: Números Primos"""

def eh_primo(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

print(eh_primo(7))  # Retorna True, pois 7 é primo

def eh_primo(numero):
    if numero <= 1:
        return False
    for i in range(2, int(numero ** 0.5) + 1):
        if numero % i == 0:
            return False
    return True

# Pede ao usuário para definir o intervalo
inicio = int(input("Digite o início do intervalo: "))
fim = int(input("Digite o fim do intervalo: "))

# Encontra e imprime os números primos no intervalo
print(f"Números primos entre {inicio} e {fim}:")
for num in range(inicio, fim + 1):
    if eh_primo(num):
        print(num)